# Generated by Django 6.1 on 2026-08-21 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_devicetype_manufacturer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=40, unique=True)),
                ('serial_number', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('IN', 'In Storage'), ('UR', 'Under Repair'), ('RE', 'Retired'), ('DI', 'Disposed')], max_length=5)),
                ('status_note', models.CharField(blank=True, max_length=100)),
                ('general_note', models.TextField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_devices', to=settings.AUTH_USER_MODEL)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.devicetype')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.location')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.manufacturer')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('manufacturer', 'serial_number'), name='unique_manufacturer_serial')],
            },
        ),
    ]
