# Generated by Django 6.1 on 2026-08-24 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mac_address', models.CharField(max_length=20)),
                ('network_interface_type', models.CharField(choices=[('ET', 'Ethernet'), ('WF', 'Wi-Fi'), ('FB', 'Fiber'), ('VT', 'Virtual')], max_length=10)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.device')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('device', 'name'), name='unique_device_name')],
            },
        ),
    ]
