# Generated by Django 6.1 on 2026-08-24 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_networkinterface'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('prefix', models.PositiveSmallIntegerField()),
                ('assignment_method', models.CharField(choices=[('ST', 'Static'), ('DHCP', 'Dynamic Host Configuration Protocol')], max_length=4)),
                ('network_interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.networkinterface')),
            ],
        ),
    ]
