# Generated by Django 6.1 on 2026-08-24 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_ipaddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('AC', 'Active'), ('IN', 'In Storage'), ('UR', 'Under Repair'), ('RE', 'Retired'), ('DI', 'Disposed')], max_length=4)),
                ('new_status', models.CharField(choices=[('AC', 'Active'), ('IN', 'In Storage'), ('UR', 'Under Repair'), ('RE', 'Retired'), ('DI', 'Disposed')], max_length=4)),
                ('status_note', models.CharField(blank=True, max_length=100)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='locations.device')),
            ],
        ),
    ]
