# Generated by Django 6.1 on 2026-09-01 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_devicestatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkinterface',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_interfaces', to='locations.device'),
        ),
    ]
