# Generated by Django 6.1 on 2026-09-01 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_alter_networkinterface_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='network_interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='locations.networkinterface'),
        ),
    ]
