# Generated by Django 6.1 on 2026-08-26 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketassignmenthistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('QUEUE', 'Queued'), ('PROG', 'In Progress'), ('WAIT', 'Waiting'), ('DEFER', 'Deferred'), ('SOLVED', 'Resolved')], max_length=6, null=True)),
                ('new_status', models.CharField(choices=[('QUEUE', 'Queued'), ('PROG', 'In Progress'), ('WAIT', 'Waiting'), ('DEFER', 'Deferred'), ('SOLVED', 'Resolved')], max_length=6)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=80)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_status_history', to='tickets.ticket')),
            ],
        ),
    ]
